version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 15
  target-branch: dev
  ignore:
    - dependency-name: "kotlinx-coroutines-android"
      versions: ["1.3.9-native-mt"]
  reviewers:
  - marcauberer
  assignees:
  - marcauberer
