language: android
jdk: oraclejdk8
android:
  components:
  - build-tools-29.0.3
  - android-29
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- chmod +x gradlew
- tar xvf secrets.tar
before_script:
- echo yes | android update sdk --no-ui --all --filter platform-tools,tools
- echo yes | android update sdk --no-ui --all --filter build-tools-29.0.3
- echo yes | android update sdk --no-ui --all --filter android-29
script:
- "./gradlew clean test"
